### ISSUE TITLE
Does this impl of mjml support conditionals? 

### ISSUE THREAD

**Issue by Simonl9l** [SebastianStehle/mjml-net#149]
per: 
```xml
<mj-raw>{% if 'value' == '' %}</mj-raw>
     <mj-text>True</mj-text>
<mj-raw>{% else %}</mj-raw>
    <mj-text>False</mj-text>
<mj-raw>{% endif %}</mj-raw>
```

**Comment by SebastianStehle** [comment]
Yes and no. You can use it together with liquid: https://github.com/sebastienros/fluid

But conditionals are not part of the spec.

**Comment by LiamRiddell** [comment]
> 
> 
> per: 
> 
> ```xml
> 
> <mj-raw>{% if 'value' == '' %}</mj-raw>
> 
>      <mj-text>True</mj-text>
> 
> <mj-raw>{% else %}</mj-raw>
> 
>     <mj-text>False</mj-text>
> 
> <mj-raw>{% endif %}</mj-raw>
> 
> ```

This was why https://github.com/Spinks90/MailChemist was born. 

However, it's going through a rewrite due to newer language features for C# being available (e.g. Source Generators). 

Furthermore, it will have an integration with MJML.Net.

I still think it's a good reference for getting dynamic emails as you require.
