### ISSUE TITLE
Request for .net core version

### ISSUE THREAD

**Issue by Abenezer** [SebastianStehle/mjml-net#188]
I am impressed by the performance and not having to request online service. but we couldnt work on production because we use .net core. is there any chance you port the library to .net core or .net standard?

Thankyou

**Comment by SebastianStehle** [comment]
I have no plans to work on this myself. If you need it you have to provide a PR.

**Comment by gliljas** [comment]
I have a working branch for net472, mostly solved by using the Polyfill NuGet. Had to add a couple pragmas and turn IType into an abstract class, since default implementations in interfaces is not supported. 

It's certainly significantly slower, but not necessarily prohibitively so (about 2x). Also, I haven't really dug into optimizing things. Just wanted to make it compile and get green tests.

**Comment by SebastianStehle** [comment]
Closed due to inactivity
