### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by marclleres** [SebastianStehle/mjml-net#196]
Hi

We are switching from version 1.24.0 to 3.11.0 and we have some strange behaviour on validation.

From our test, using "SoftValidator.Instance" for validation on MjmlRenderer.

* It does test that tag is a MJML knowned tag and give error if not:

```
    <mjml><mj-body><a href=https://www.google.com/>My Link</mj-body></mjml> is on error
```

* It does not test if the tag is correct when Mjml tag is final

```
    <mjml><mj-body><mj-section><mj-column><mj-text><ari href=https://www.google.com/ >My Link</are></mj-text></mj-column></mj-section></mj-body></mjml> works
```

* It does not check if text is in a final mjml tag and does not generate HTML

```
    <mjml><mj-body><mj-body>My Text</mj-body></mj-body></mjml> does not give error but does not generate html
 ```

* It does not check that mjml tag are closed but generate it:

```
    <mjml><mj-body><mj-section><mj-column><mj-text>MyText</mjml> does not give errror, but generate html
```

Are those comportement are what expected?

Is it normal to not check that validators do not check that the tag is final when there is no tag inside?

Is it normal to not check closing tag and still generate html ?

 

Thanks

 
Regards

 
Marc

**Comment by SebastianStehle** [comment]
Can you just show the error? I don't understand the problem tbh.

**Comment by SebastianStehle** [comment]
## Example 1

```
<mjml><mj-body><a href=https://www.google.com/>My Link</mj-body></mjml
```

mj-body does not accept raw html. 

## Example 2

```
<mjml><mj-body><mj-section><mj-column><mj-text><ari href=https://www.google.com/ >My Link</are></mj-text></mj-column></mj-section></mj-body></mjml> works
```

This is correct because mj-text accepts raw/arbitrary html.

## Example 3

```
 <mjml><mj-body><mj-body>My Text</mj-body></mj-body></mjml>
```

Returns the following error:

```
'mj-body' must be child of 'mjml', found 'mj-body'
```

The rendering for mj-body is so special, we have never tested what happens when you nest that. It somehow produces an output, but not what you expect. There are no plans to change that, because not all errors can be handled properly.

## Example 4

```
<mjml><mj-body><mj-section><mj-column><mj-text>MyText</mjml
```

This should produce a proper error, but I am not sure how to implement that. I think with the switch to a HTML parser this stopped working, because of the differences between HTML and XML. 

I am not sure if and how we can improve that. When we start an element that accepts a raw HTML we just print the inner html to the output stream. Therefore there is no validation going on for mj-text.

**Comment by SebastianStehle** [comment]
I have pushed and published a fix / improvement.

**Comment by SebastianStehle** [comment]
I think we have no validation for this at the moment.

**Comment by marclleres** [comment]
Hello,

Yeah, it doesn't look like there is validation for this
Do you plan to add it ? 

Thanks
Regards
Marc

**Comment by SebastianStehle** [comment]
Yes, sure ... but I don't know when. Perhaps this week or the week after. PRs are also very welcome.
