### ISSUE TITLE
StringBuilder Performance

### ISSUE THREAD

**Issue by LiamRiddell** [SebastianStehle/mjml-net#97]
@SebastianStehle, what do you think about possibly trying this? https://github.com/Cysharp/ZString

**Comment by SebastianStehle** [comment]
It is worth to try, but we need some more overloads because we cannot use the interpolated trick any more.

**Comment by SebastianStehle** [comment]
If you really want to have best performance you have to do the following:

1. We basically just copy from one buffer to another. Our source is a XML buffer (UTF8) and our target as well.
2. To make it allocation efficient you have to bring data from one buffer to another without allocations.
3. The U8XMLParser does already a great job by using structs for xml objects. Every struct is basically just a pointer to the buffer. But because strings in C# are UTF8 you cannot deal with them directly.
4. If all the properties in a component are UTF8 structs AND all constant strings in your code as well you can basically copy from XML to HTML without allocations. This would give you  the best speed. Similar to https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonencodedtext?view=net-6.0

**Comment by SebastianStehle** [comment]
Lets just keep it open for now, please.
